version: '3.9'
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jumarket
    volumes:
      - jumarket-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 10s
      retries: 5
    networks:
      - bridge
  
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    restart: always

  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      mysql-server:
        condition: service_healthy
    networks:
      - bridge

volumes:
  jumarket-mysql:
  
networks:
  bridge: 
