INSERT INTO product (product_id, name, unit_of_measure, unit_price, category_id)
VALUES
    (1, 'Arroz Tio João', 'kg', 5.99, 4),
    (2, 'Feijão Carioca', 'kg', 4.99, 4),
    (3, 'Guaraná Antarctica', 'unidade', 3.49, 1),
    (4, 'Sabonete em Barra Uso Diário Dove', 'unidade', 1.99, 10),
    (5, 'Passatempo - Biscoito Recheado', 'pacote', 2.49, 7),
    (6, 'Piracanjuba - Leite Integral', 'litro', 3.99, 8),
    (7, 'Café L\'or Cápsula Ultimo', 'pacote', 27.99, 4),
    (8, 'Fondue de Chocolate Suisse', 'barra', 35.49, 3),
    (9, 'Ypê - Lava Louças Líquido Clear Care', 'unidade', 2.99, 2),
    (10, 'Pão alemão Stuttgart de Centeio Integral com Granola', 'unidade', 14.99, 7),
    (11, 'Macarrão Grano Duro Bavette N.13', 'pacote', 2.99, 4),
    (12, 'Campo Belo Conservas - Óleo misto de soja e azeitona 30%', 'litro', 4.49, 4),
    (13, 'Água Crystal 500ml', 'garrafa', 1.99, 1),
    (14, 'Shampoo 3 em 1 Dove Men+Care Sports 200Ml, Dove', 'frasco', 7.99, 10),
    (15, 'Biscoito Club Social regular original embalagem econômica 288g', 'pacote', 2.49, 7),
    (16, 'Bebida Láctea, Maçã Banana e Mamão, Neston, 280ml', 'unidade', 1.49, 8),
    (17, 'Native - Açúcar Demerara Orgânico, 1kg', 'kg', 3.99, 4),
    (18, 'Dr. Oetker Sorvete Sabor Chocolate, Pó para Preparo de Sobremesa, Consistência Cremosa e Sabor Delicioso, 150g', 'pacote', 8.99, 3),
    (19, 'Downy Paixão Perfume Collection - Amaciante Concentrado, 1,35 L', 'garrafa', 6.99, 2),
    (20, 'Dr. Oetker Bolo Tradicional Sabor Laranja, Fácil Preparo, Mistura Pronta para Massa, Sobremesa Fofinha e Saborosa, 400g', 'unidade', 12.99, 7);
